### ISSUE TITLE
Project 2 - text colour

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#15]
![firefox_2022-03-29_20-02-26](https://user-images.githubusercontent.com/102472265/160676080-75c8a202-836f-4f6e-98e7-ce48655fa6f7.png)

white text on white/gray background is barely readable
especially the small text at the bottom

also should we really use a BG where "shutterstock" watermark is still in it?
or is this just a placeholder?

**Comment by Leohsieh57** [comment]
yes that one is a place holder
i think we'll have to ask Abner to make something like that
placed there mainly for demo purpose for Abner

**Comment by Leohsieh57** [comment]
![Uploading image.png…]()
