### ISSUE TITLE
Home - text colour

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#18]
The neon yellow is too bright. A little bit less would be better. Maybe even an orangish tone like Haachamas darker hair

**Comment by Leohsieh57** [comment]
orange doesn't look good in my opinion
instead, i lowered the halo radius. please check if it's good now
![image](https://user-images.githubusercontent.com/22349791/160802841-aab1a7e8-daf9-4167-8230-0099a0ed7963.png)
