### ISSUE TITLE
Site bottom text - typo

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#19]
![firefox_2022-03-29_20-12-42](https://user-images.githubusercontent.com/102472265/160677702-a438a825-54d0-49f4-a0f6-3bc3bd08a93d.png)

First line has a "." at the end.

Should get deleted.

also can you make **All our projects are the works of fans** in bold text?

**Comment by Leohsieh57** [comment]
1. the . stands for the abrreviated corperation
2. sure will be adding it

**Comment by Leohsieh57** [comment]
![image](https://user-images.githubusercontent.com/22349791/160754806-d81a4149-58c0-4d9c-92a1-45d594af463a.png)
