### ISSUE TITLE
Previous works titles swapped

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#24]
![firefox_2022-04-02_15-39-58](https://user-images.githubusercontent.com/102472265/161385960-09de21cb-53c2-4dfb-9fe8-9be3e3ea1d47.png)

The titles got swapped around by mistake

**Comment by wws-haato** [comment]
![image](https://user-images.githubusercontent.com/100846292/161386332-912fa080-7c5d-40c4-a0d7-e637f4fbd447.png)
fixed
