### ISSUE TITLE
About: Old text, needs update

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#25]
![firefox_2022-04-02_15-43-08](https://user-images.githubusercontent.com/102472265/161386056-8263e453-1bc4-49d7-846f-6276e3fb990b.png)

This text was copy-pasted from the time we had only 1 project. Its outdated.

Instead of "We have so far produced our first project "World Wide Tour Guide" and will be continuing to make more supportive projects for Haachama in the future."

--->

So far we have successfully produced two projects and celebrated our first anniversary as a fan group.
We will continue to make more supportive projects for Haachama in the future.

**Comment by henry4204aaa** [comment]
done
