### ISSUE TITLE
Current event - overview

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#26]
![firefox_2022-04-02_15-47-31](https://user-images.githubusercontent.com/102472265/161386227-6ea9a9a9-57aa-4242-a7f4-29d38fb4a9d4.png)

Haachamachama! We are team WWS Haato, dedicated to fan-based
projects for Haato which gathering fans all over the world!
This year, as Haachama is strong enough to face the difficulties in
the future, we would like to present a visual novel for our strongest
idol Haachama as a birthday gift in 2022!
　　　　
We're going to recruit particapants from different field, including
storywriting, programmars, illustrators, musicians and testers!
Your contribution is always welcome!

--->
(just copy paste the whole text)

Haachamachama! We are team WWS Haato, dedicated to fan-based
projects for Haato which gather fans all over the world!
As Haachama is strong enough to face the difficulties that lie ahead in the future, we want to gift her something special for her birthday.
This year we present our own visual novel where players can walk the path of our strongest idol, interact with others and become a star!
　　　　
We're going to recruit participants from different fields, including
storywriters, programmars, illustrators, musicians and testers!
Your contribution is always welcome!

**Comment by henry4204aaa** [comment]
programmers

**Comment by henry4204aaa** [comment]
Done. Will close after pull request
