### ISSUE TITLE
project 1 - Concept of World Wide

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#5]
We clustered photos continent-wise to show that Haachama's fanbase uniformly distributes over the world, featuring some supportive messages from the corresponding continents.

--->

We clustered photos continent-wise to show that Haachama is truly a World Wide Idol and has fans everywhere.
In the end of the video we showed supportive messages collected from different continents.

**Comment by Leohsieh57** [comment]
![image](https://user-images.githubusercontent.com/22349791/160782686-543b57a1-f1a2-4e31-9603-e6a562cb7fe8.png)
