### ISSUE TITLE
Start site - visibility

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#6]
I feel we could add something like a scroll down or ↓ button on the start site

For some it might not be intuitive to scroll down, but instead click instantly on the menu in the top left and they will miss our introduction

**Comment by Leohsieh57** [comment]
you mean an arrow-like indicator as a hint for users to scroll down ?
or an actual button that scrolls the page downwards while clicking?

i personally think the former would be a good solution

**Comment by Leohsieh57** [comment]
> I feel we could add something like a scroll down or ↓ button on the start site
> 
> For some it might not be intuitive to scroll down, but instead click instantly on the menu in the top left and they will miss our introduction

you mean an arrow-like indicator as a hint to tell users to scroll down on their own?
or an actually clickable button that scrolls the page downwards while pushed?

i personally think the former would be a good solution

**Comment by Zhadar1** [comment]
yeah, the former is enough
