### ISSUE TITLE
Monetization (bottom of start site)

### ISSUE THREAD

**Issue by Zhadar1** [wws-haato/wws-haato.github.io#7]
none of our productions would ever be monetized

--->

We are non profit team.
We don't have an official business relationship with Cover Corp.
We are not representing Haachama or other parts of Hololive.

**All our projects are the works of fans.**
We allow Haachama to use our works for her streams and own projects.
This may include her own monetization.

sounds a bit better and makes clear that we are following their fan work guidance

**Comment by Leohsieh57** [comment]
![image](https://user-images.githubusercontent.com/22349791/160563319-95159081-e925-4404-a0a6-d30fa9a1bf5a.png)
